# This workflow will run tests using node

name: Build containers

on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Get the tag
        id: get_version
        uses: battila7/get-version-action@v2
      -
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.3
      -
        working-directory: ./site
        env:
         BC_VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          npm ci
          npx nuxt generate --fail-on-error --dotenv false
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push web server
        uses: docker/build-push-action@v2
        with:
          context: ./site
          file: ./build/web-server.dockerfile
          push: true
          tags: ppissanetzky/barcode-web-server:${{ steps.get_version.outputs.version }}
      -
        name: Build and push API server
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./build/api-server.dockerfile
          push: true
          tags: ppissanetzky/barcode-api-server:${{ steps.get_version.outputs.version }}
      -
        name: Create target .env
        runs: |
          	echo "VERSION=${{ steps.get_version.outputs.version }}" > ./build/target/barcode-prod/.env
          	echo "VERSION=${{ steps.get_version.outputs.version }}" > ./build/target/barcode-demo/.env
      -
        name: Upload target artifact
        uses: actions/upload-artifact@v2
        with:
          name: target-${{ steps.get_version.outputs.version }}
          path: ./build/target/
