# This workflow will run tests using node

name: Run tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.3
      - run: npm ci
      - env:
          BC_XF_API_KEY: ${{ secrets._BC_XF_API_KEY }}
        run: npm test
